

backend:
  name: github
  repo: Damian2626/DecapCMS-Test
  branch: main


media_folder: "static/img"
public_folder: "docs"

collections:
  - name: "docs"
    label: "Documentation"
    folder: "docs"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Contenu", name: "body", widget: "markdown" }

